# Generated by Django 6.0.5 on 2026-05-13 13:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuxiliaryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(db_index=True, max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("audit", "audit"), ("file_access", "file_access")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="UnknownMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=255, unique=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="CleanSyncFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=255, unique=True)),
                (
                    "requested_sync_type",
                    models.CharField(
                        choices=[
                            ("CLEAN", "Clean"),
                            ("CLEAN_ALL", "Clean All"),
                            ("CLEAN_STANDALONE", "Clean Standalone"),
                            ("CLEAN_RULES", "Clean Rules"),
                            ("CLEAN_FILE_ACCESS_RULES", "Clean File Access Rules"),
                        ],
                        default="CLEAN",
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("set_at", models.DateTimeField(auto_now_add=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-set_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(db_index=True, max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "file_sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=512
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=48
                    ),
                ),
                (
                    "executing_user",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "execution_time",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("logged_in_users", models.JSONField(blank=True, default=list)),
                ("current_sessions", models.JSONField(blank=True, default=list)),
                (
                    "file_bundle_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "file_bundle_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "file_bundle_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "file_bundle_executable_rel_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "file_bundle_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "file_bundle_version_string",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "file_bundle_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("file_bundle_hash_millis", models.IntegerField(blank=True, null=True)),
                (
                    "file_bundle_binary_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("ppid", models.IntegerField(blank=True, null=True)),
                (
                    "parent_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "signing_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "team_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "cdhash",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "quarantine_data_url",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "quarantine_referer_url",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("quarantine_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "quarantine_agent_bundle_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("signing_chain", models.JSONField(blank=True, default=list)),
                ("entitlement_info", models.JSONField(blank=True, default=dict)),
                ("cs_flags", models.BigIntegerField(blank=True, null=True)),
                (
                    "signing_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("secure_signing_time", models.DateTimeField(blank=True, null=True)),
                ("signing_time", models.DateTimeField(blank=True, null=True)),
                ("static_rule", models.BooleanField(default=False)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["machine_id", "received_at"],
                        name="app_event_machine_16d2c9_idx",
                    ),
                    models.Index(
                        fields=["audience", "decision"],
                        name="app_event_audienc_5ff9f0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("BINARY", "Binary"),
                            ("CERTIFICATE", "Certificate"),
                            ("SIGNINGID", "Signingid"),
                            ("TEAMID", "Teamid"),
                            ("CDHASH", "Cdhash"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "policy",
                    models.CharField(
                        choices=[
                            ("ALLOWLIST", "Allowlist"),
                            ("ALLOWLIST_COMPILER", "Allowlist Compiler"),
                            ("BLOCKLIST", "Blocklist"),
                            ("SILENT_BLOCKLIST", "Silent Blocklist"),
                            ("REMOVE", "Remove"),
                            ("CEL", "Cel"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "custom_msg",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "custom_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "notification_app_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cel_expr", models.TextField(blank=True, default="")),
                ("applies_to_students", models.BooleanField(default=False)),
                ("applies_to_teachers", models.BooleanField(default=False)),
                (
                    "creation_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["updated_at", "id"], name="app_rule_updated_a46d42_idx"
                    ),
                    models.Index(
                        fields=["applies_to_students"],
                        name="app_rule_applies_f41a3b_idx",
                    ),
                    models.Index(
                        fields=["applies_to_teachers"],
                        name="app_rule_applies_2fff15_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("identifier", "rule_type"), name="uniq_identifier_type"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("applies_to_students", True),
                            ("applies_to_teachers", True),
                            _connector="OR",
                        ),
                        name="rule_has_audience",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("machine_id", models.CharField(db_index=True, max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CLEAN", "Clean"),
                            ("CLEAN_ALL", "Clean All"),
                            ("CLEAN_STANDALONE", "Clean Standalone"),
                            ("CLEAN_RULES", "Clean Rules"),
                            ("CLEAN_FILE_ACCESS_RULES", "Clean File Access Rules"),
                        ],
                        default="NORMAL",
                        max_length=32,
                    ),
                ),
                (
                    "client_mode",
                    models.CharField(
                        choices=[
                            ("MONITOR", "Monitor"),
                            ("LOCKDOWN", "Lockdown"),
                            ("STANDALONE", "Standalone"),
                        ],
                        default="MONITOR",
                        max_length=16,
                    ),
                ),
                ("batch_size", models.PositiveIntegerField(default=50)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rules_sent", models.PositiveIntegerField(default=0)),
                ("rules_received", models.PositiveIntegerField(default=0)),
                ("rules_processed", models.PositiveIntegerField(default=0)),
                (
                    "postflight_sync_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "client_rules_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "final_rules_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("consumed_clean_flag", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["machine_id", "completed_at"],
                        name="app_syncses_machine_0ad93c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                (
                    "token",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("last_rule_pk", models.BigIntegerField()),
                ("last_updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursors",
                        to="app.syncsession",
                    ),
                ),
            ],
        ),
    ]
