# Generated by Django 6.0.5 on 2026-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerSettings",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "monitor_only",
                    models.BooleanField(
                        default=False,
                        help_text="When on, sync responses force client_mode=MONITOR and ruledownload returns no rules. Block events are still captured. Deploy policy via the downloadable mobileconfigs.",
                    ),
                ),
                (
                    "mobileconfig_client_mode",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "MONITOR"), (2, "LOCKDOWN"), (3, "STANDALONE")],
                        default=2,
                        help_text="ClientMode value (integer) embedded in generated .mobileconfig payloads.",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        default="elf",
                        help_text="PayloadOrganization shown in System Settings → Profiles.",
                        max_length=128,
                    ),
                ),
                (
                    "payload_identifier_prefix",
                    models.CharField(
                        default="com.elf.santa",
                        help_text="Reverse-DNS prefix for mobileconfig PayloadIdentifier values.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Server settings",
                "verbose_name_plural": "Server settings",
            },
        ),
    ]
