# Generated by Django 6.0.5 on 2026-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_serversettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="applies_to_students",
            field=models.BooleanField(
                default=False,
                help_text='Send this rule to machines whose machine_id contains "STU", and include it in the Students .mobileconfig download.',
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="applies_to_teachers",
            field=models.BooleanField(
                default=False,
                help_text='Send this rule to machines whose machine_id contains "EMP", and include it in the Teachers .mobileconfig download. (At least one of Students or Teachers must be checked.)',
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="cel_expr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required only when Policy = CEL. A Common Expression Language expression evaluated at execution time; must return ALLOWLIST/BLOCKLIST or a boolean. Leave blank for non-CEL policies.",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="custom_msg",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional. Shown to the user in the block dialog when this rule fires. Overrides Santa's default block message. Used only for BLOCK_* policies.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="custom_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Optional. URL behind the "Open" button on the block dialog. Supports Santa placeholders like %file_sha%, %machine_id%, %username%.',
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="identifier",
            field=models.CharField(
                db_index=True,
                help_text="The value being matched. Format depends on Rule type: BINARY → 64-char SHA-256 of the file; CERTIFICATE → 64-char SHA-256 of the leaf signing certificate; TEAMID → 10-char Apple Developer Team ID (e.g. EQHXZ8M8AV); SIGNINGID → TeamID:bundle-id (e.g. EQHXZ8M8AV:com.google.Chrome), or platform:&lt;name&gt; for macOS-bundled binaries; CDHASH → 40-char hex code-directory hash from the signature.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="notification_app_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Optional. When this rule un-blocks a previously-blocked app, Santa shows a "now allowed" notification using this name. Set it to the user-visible app name (e.g. "Slack").',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="policy",
            field=models.CharField(
                choices=[
                    ("ALLOWLIST", "Allowlist"),
                    ("ALLOWLIST_COMPILER", "Allowlist Compiler"),
                    ("BLOCKLIST", "Blocklist"),
                    ("SILENT_BLOCKLIST", "Silent Blocklist"),
                    ("REMOVE", "Remove"),
                    ("CEL", "Cel"),
                ],
                help_text="What Santa does on match. ALLOWLIST = allow. ALLOWLIST_COMPILER = allow and treat outputs of this binary as locally allowed (needs transitive rules enabled; use sparingly). BLOCKLIST = deny and show the block dialog. SILENT_BLOCKLIST = deny with no dialog. REMOVE = delete any previously-synced rule with the same identifier and type (no effect in a mobileconfig — sync-only). CEL = evaluate the CEL expression below at decision time.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("BINARY", "Binary"),
                    ("CERTIFICATE", "Certificate"),
                    ("SIGNINGID", "Signingid"),
                    ("TEAMID", "Teamid"),
                    ("CDHASH", "Cdhash"),
                ],
                help_text="How the identifier is interpreted. BINARY = exact file (very narrow). CERTIFICATE = anything signed by that cert. TEAMID = anything signed by that Apple Developer Team (survives cert rotation, broadest). SIGNINGID = a specific signed binary by its signing ID (narrower than TEAMID). CDHASH = a specific signed binary version (tightest signed-binary match).",
                max_length=16,
            ),
        ),
    ]
