# Generated by Django 6.0.5 on 2026-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_rule_applies_to_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes for admins (why this rule exists, ticket links, etc.). Never sent to Santa clients or included in mobileconfig downloads.",
            ),
        ),
    ]
