# Generated by Django 6.0.5 on 2026-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rule_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="serversettings",
            name="allowed_path_regex",
            field=models.CharField(
                blank=True,
                default="^/(?:System|usr/(?:bin|libexec|sbin))/",
                help_text="ICU regex. Executions from paths matching this pattern are allowed when no other rule matches. Emitted as <code>AllowedPathRegex</code> in the mobileconfig and as <code>allowed_path_regex</code> in preflight responses. Leave blank to omit. Note: anything writable into these paths effectively bypasses Santa, so keep it tight.",
                max_length=1024,
            ),
        ),
    ]
