# Generated by Django 6.0.5 on 2026-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_backfill_unknown_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auxiliaryevent",
            name="audience",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("student", "Student")],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="audience",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("student", "Student")],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="syncsession",
            name="audience",
            field=models.CharField(
                choices=[("teacher", "Teacher"), ("student", "Student")], max_length=16
            ),
        ),
    ]
