# Generated by Django 6.0.5 on 2026-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_split_student_into_middle_and_upper_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncsession",
            name="hostname",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="machine_owner",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="model_identifier",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="os_build",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="os_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="primary_user",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="santa_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="serial_num",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
