# Generated by Django 6.0.5 on 2026-05-14 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_syncsession_hostname_syncsession_machine_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="serversettings",
            name="default_client_mode",
            field=models.CharField(
                choices=[
                    ("MONITOR", "Monitor"),
                    ("LOCKDOWN", "Lockdown"),
                    ("STANDALONE", "Standalone"),
                ],
                default="MONITOR",
                help_text="Mode pushed to clients in preflight unless a per-machine override exists. Per-machine overrides are set from each machine's detail page.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="serversettings",
            name="monitor_only",
            field=models.BooleanField(
                default=False,
                help_text="Emergency switch. When on, sync forces MONITOR and ruledownload returns no rules — overrides both the global default and any per-machine settings.",
            ),
        ),
        migrations.CreateModel(
            name="MachinePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_id", models.CharField(max_length=255, unique=True)),
                (
                    "client_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MONITOR", "Monitor"),
                            ("LOCKDOWN", "Lockdown"),
                            ("STANDALONE", "Standalone"),
                        ],
                        default="",
                        help_text="Leave blank to use the global default.",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["machine_id"],
            },
        ),
    ]
