# Generated by Django 6.0.5 on 2026-05-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_serversettings_default_client_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serversettings",
            name="banned_block_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown when a binary is blocked because a BLOCKLIST rule matches it. Per-rule <em>Block dialog → Custom message</em> on the matching Rule overrides this.",
            ),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="event_detail_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Label for the "Open Event" button. Defaults to Santa\'s built-in text when blank.',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="event_detail_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text='URL template for the "Open Event" button in the block dialog. Supports Santa placeholders: <code>%machine_id%</code>, <code>%username%</code>, <code>%file_identifier%</code>, <code>%file_bundle_id%</code>, <code>%signing_id%</code>, <code>%team_id%</code>. Leave blank to hide the button.',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="mode_notification_lockdown",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notification banner shown when the client transitions into LOCKDOWN mode.",
            ),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="mode_notification_monitor",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notification banner shown when the client transitions into MONITOR mode.",
            ),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="unknown_block_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown when an unsigned/unknown binary is blocked because no rule covers it (LOCKDOWN mode). Supports basic HTML.",
            ),
        ),
    ]
