# Generated by Django 6.0.5 on 2026-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_serversettings_banned_block_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serversettings",
            name="mobileconfig_client_mode",
        ),
        migrations.RemoveField(
            model_name="serversettings",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="serversettings",
            name="payload_identifier_prefix",
        ),
        migrations.AlterField(
            model_name="rule",
            name="applies_to_middle_school",
            field=models.BooleanField(
                default=False,
                help_text='Send this rule to machines whose machine_id starts with "MS-".',
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="applies_to_teachers",
            field=models.BooleanField(
                default=False,
                help_text='Send this rule to machines whose machine_id contains "EMP". (At least one audience must be checked.)',
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="applies_to_upper_school",
            field=models.BooleanField(
                default=False,
                help_text='Send this rule to machines whose machine_id starts with "US-" (also the default audience for unrecognized machines).',
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Internal notes for admins (why this rule exists, ticket links, etc.). Never sent to Santa clients.",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="policy",
            field=models.CharField(
                choices=[
                    ("ALLOWLIST", "Allowlist"),
                    ("ALLOWLIST_COMPILER", "Allowlist Compiler"),
                    ("BLOCKLIST", "Blocklist"),
                    ("SILENT_BLOCKLIST", "Silent Blocklist"),
                    ("REMOVE", "Remove"),
                    ("CEL", "Cel"),
                ],
                help_text="What Santa does on match. ALLOWLIST = allow. ALLOWLIST_COMPILER = allow and treat outputs of this binary as locally allowed (needs transitive rules enabled; use sparingly). BLOCKLIST = deny and show the block dialog. SILENT_BLOCKLIST = deny with no dialog. REMOVE = delete any previously-synced rule with the same identifier and type. CEL = evaluate the CEL expression below at decision time.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="serversettings",
            name="allowed_path_regex",
            field=models.CharField(
                blank=True,
                default="^/(?:System|usr/(?:bin|libexec|sbin))/",
                help_text="ICU regex. Executions from paths matching this pattern are allowed when no other rule matches. Emitted as <code>allowed_path_regex</code> in preflight responses. Leave blank to omit. Note: anything writable into these paths effectively bypasses Santa, so keep it tight.",
                max_length=1024,
            ),
        ),
    ]
