# Generated by Django 6.0.5 on 2026-05-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_serversettings_mobileconfig_client_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serversettings",
            name="banned_block_message",
        ),
        migrations.RemoveField(
            model_name="serversettings",
            name="mode_notification_lockdown",
        ),
        migrations.RemoveField(
            model_name="serversettings",
            name="mode_notification_monitor",
        ),
        migrations.RemoveField(
            model_name="serversettings",
            name="unknown_block_message",
        ),
    ]
