# Generated by Django 6.0.5 on 2026-05-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_drop_nonsync_block_dialog_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="serversettings",
            name="middle_school_client_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONITOR", "Monitor"),
                    ("LOCKDOWN", "Lockdown"),
                    ("STANDALONE", "Standalone"),
                ],
                default="",
                help_text="Mode for MS-* machines. Leave blank to fall back to the global default.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="teacher_client_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONITOR", "Monitor"),
                    ("LOCKDOWN", "Lockdown"),
                    ("STANDALONE", "Standalone"),
                ],
                default="",
                help_text='Mode for machines whose ID contains "EMP". Leave blank to fall back to the global default.',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="upper_school_client_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONITOR", "Monitor"),
                    ("LOCKDOWN", "Lockdown"),
                    ("STANDALONE", "Standalone"),
                ],
                default="",
                help_text="Mode for US-* machines (and unrecognized machine IDs, which route to upper school). Leave blank to fall back to the global default.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="serversettings",
            name="default_client_mode",
            field=models.CharField(
                choices=[
                    ("MONITOR", "Monitor"),
                    ("LOCKDOWN", "Lockdown"),
                    ("STANDALONE", "Standalone"),
                ],
                default="MONITOR",
                help_text="Fallback mode pushed to clients when neither a per-machine override nor an audience-level override applies. Per-machine overrides are set from each machine's detail page.",
                max_length=16,
            ),
        ),
    ]
