# Generated by Django 6.0.6 on 2026-06-10 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_serversettings_middle_school_client_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=255, unique=True)),
                ('audience', models.CharField(choices=[('teacher', 'Teacher'), ('middle_school', 'Middle School'), ('upper_school', 'Upper School')], db_index=True, max_length=16)),
                ('machine_owner', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('primary_user', models.CharField(blank=True, default='', max_length=255)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('serial_num', models.CharField(blank=True, default='', max_length=128)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('os_build', models.CharField(blank=True, default='', max_length=64)),
                ('model_identifier', models.CharField(blank=True, default='', max_length=128)),
                ('santa_version', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_completed', models.DateTimeField(blank=True, null=True)),
                ('sync_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='app_machine_last_se_093bff_idx'), models.Index(fields=['-sync_count'], name='app_machine_sync_co_733194_idx')],
            },
        ),
    ]
