# Generated by Django 6.0.8 on 2026-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # 0016 empties the cursor table first: rows minted by the old one-shot
        # scheme can duplicate (session, last_rule_pk), which the constraint
        # added at the end of this migration would reject.
        ('app', '0016_purge_sync_cursors'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccursor',
            name='sent_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='clean_flag_kept_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='consumed_clean_flag_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleansyncflag',
            name='requested_sync_type',
            field=models.CharField(choices=[('CLEAN_ALL', 'Clean All')], default='CLEAN_ALL', help_text="Every sync is already a CLEAN sync, which drops previously-synced rules. Queue CLEAN_ALL to also drop transitive and standalone-approved rules on the machine's next sync.", max_length=32),
        ),
        migrations.AlterField(
            model_name='synccursor',
            name='last_rule_pk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synccursor',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncsession',
            name='sync_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CLEAN', 'Clean'), ('CLEAN_ALL', 'Clean All'), ('CLEAN_STANDALONE', 'Clean Standalone'), ('CLEAN_RULES', 'Clean Rules'), ('CLEAN_FILE_ACCESS_RULES', 'Clean File Access Rules')], default='CLEAN', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='synccursor',
            constraint=models.UniqueConstraint(fields=('session', 'last_rule_pk'), name='uniq_cursor_position'),
        ),
    ]
