# Generated by Django 6.0.6 on 2026-09-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_backfill_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='disable_unknown_event_upload',
            field=models.BooleanField(default=False, help_text='When on, clients stop uploading ALLOW_UNKNOWN events — unknown binaries allowed because the machine is in MONITOR mode. Normally leave off: those events are how new software gets noticed and turned into rules.'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='enable_all_event_upload',
            field=models.BooleanField(default=False, help_text='When on, clients upload every execution event, including ones already allowed by a rule. Useful for a short debugging window; expect a large jump in event volume.'),
        ),
    ]
