# Generated by Django 6.0.8 on 2026-09-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_serversettings_disable_unknown_event_upload_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(condition=models.Q(('abandoned_at__isnull', True), ('completed_at__isnull', True)), fields=['-started_at'], name='syncsession_in_flight_idx'),
        ),
    ]
