# Generated by Django 6.0.9 on 2026-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_syncsession_syncsession_in_flight_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rule',
            name='rule_has_audience',
        ),
        migrations.AddField(
            model_name='rule',
            name='applies_to_sixth_grade',
            field=models.BooleanField(default=False, help_text='Send this rule to machines whose machine_id starts with "6TH-".'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='sixth_grade_client_mode',
            field=models.CharField(blank=True, choices=[('MONITOR', 'Monitor'), ('LOCKDOWN', 'Lockdown'), ('STANDALONE', 'Standalone')], default='MONITOR', help_text='Mode for 6TH-* machines. Starts at MONITOR because the 6th grade ruleset starts empty. Leave blank to fall back to the global default.', max_length=16),
        ),
        migrations.AlterField(
            model_name='auxiliaryevent',
            name='audience',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('sixth_grade', '6th Grade'), ('middle_school', 'Middle School'), ('upper_school', 'Upper School')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('sixth_grade', '6th Grade'), ('middle_school', 'Middle School'), ('upper_school', 'Upper School')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='machine',
            name='audience',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('sixth_grade', '6th Grade'), ('middle_school', 'Middle School'), ('upper_school', 'Upper School')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='syncsession',
            name='audience',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('sixth_grade', '6th Grade'), ('middle_school', 'Middle School'), ('upper_school', 'Upper School')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['applies_to_sixth_grade'], name='app_rule_applies_21cf18_idx'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.CheckConstraint(condition=models.Q(('applies_to_sixth_grade', True), ('applies_to_middle_school', True), ('applies_to_upper_school', True), ('applies_to_teachers', True), _connector='OR'), name='rule_has_audience'),
        ),
    ]
